### ISSUE TITLE
Configuration location for the sync server

### ISSUE THREAD

**Issue by gaining** [nrobinaubertin/dockerfiles#2]
Hello, 

After using your ffsync server docker implementation. I used nginx as a reverse proxy. So far it works for syncing between desktop clients on both windows and linux but it doesn't for Android 8.

I found out that I need to change `force_wsgi_environ = false` to true because I'm not using the default port 5000 due to the proxy. I don't know where the config file is.

**Comment by nrobinaubertin** [comment]
Hi,
I never had to change it. I will add a environment variable to the container to enable it.  
In the mean time you can change it yourself by editing the corresponding line in the `run.sh` file. I'm creating the config file with this script.

**Comment by gaining** [comment]
So I have to uninstall it, remove the docker image and containers, edit the run.sh, rebuilt it using the edited run.sh that enables force_wsgi_environ to run it again?

**Comment by nrobinaubertin** [comment]
Yes, exactly

**Comment by gaining** [comment]
Ok thanks

**Comment by gaining** [comment]
That fixed my problem with android
